import type { Metadata } from "next";

import "./globals.css";
import { Geist } from 'next/font/google'


export const metadata: Metadata = {
  title: "Achme the summarizer",
  description: "Generated by create next app",
};

const geist = Geist({
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={geist.className}>
      <body
      >
        {children}
      </body>
    </html>
  );
}
