import type { Metadata } from "next";
import "./globals.css";
import { Geist } from 'next/font/google'
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Adaptive ai the summarizer",
  description: "Generated by create next app",
};

const geist = Geist({
  subsets: ['latin'],
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={geist.className}>
      <body
      >
        {children}
          <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
